version: "3.9"

services:

  job_scheduler:
    build:
      context: ./backend/job-scheduler
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      database:
        condition: service_healthy
    environment:
      POSTGRES_HOST: "database"
      POSTGRES_PORT: "8083"
      POSTGRES_DB: "steam-status-checker"
      POSTGRES_USER: "dbotas"
      POSTGRES_PASSWORD: "dbotaspass"
    networks:
      - backend

  web_api:
    build:
      context: ./backend/web-api
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    depends_on:
      job_scheduler:
        condition: service_started
      database:
        condition: service_healthy
    environment:
      POSTGRES_HOST: "database"
      POSTGRES_PORT: "8083"
      POSTGRES_DB: "steam-status-checker"
      POSTGRES_USER: "dbotas"
      POSTGRES_PASSWORD: "dbotaspass"
      PORT: "8082"
    networks:
      - backend

  database:
    image: postgres:16
    restart: unless-stopped
    hostname: postgres
    environment:
      POSTGRES_DB: "steam-status-checker"
      POSTGRES_USER: "dbotas"
      POSTGRES_PASSWORD: "dbotaspass"
      PGPORT: "8083"
    expose:
      - "8083"
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dbotas -d steam-status-checker -p 8083"]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  backend:
