version: "3.8"

# TODO: sometimes booting everything from web_api in cascade fails. try to introduce a timeout
services:

  job_scheduler:
    build:
      context: ./backend/job-scheduler
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - database
    environment:
      POSTGRES_HOST: "host.docker.internal"
      POSTGRES_PORT: "8083"
      POSTGRES_DB: "steam-status-checker"
      POSTGRES_USER: "dbotas"
      POSTGRES_PASSWORD: "dbotaspass"
    networks:
      - backend

  web_api:
    build:
      context: ./backend/web-api
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    depends_on:
      - job_scheduler
    environment:
      POSTGRES_HOST: "host.docker.internal"
      POSTGRES_PORT: "8083"
      POSTGRES_DB: "steam-status-checker"
      POSTGRES_USER: "dbotas"
      POSTGRES_PASSWORD: "dbotaspass"
      PORT: "8082"
    networks:
      - backend

  database:
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_DB: "steam-status-checker"
      POSTGRES_USER: "dbotas"
      POSTGRES_PASSWORD: "dbotaspass"
    expose:
      - "8083"
    ports:
      - "8083:8083"
    command: -p 8083
    networks:
      - backend

networks:
  backend:
